variables:
  # leave following comment to enable renovate bot for terraform image
  # renovate: datasource=docker depName=hashicorp/terraform
  TERRAFORM_IMAGE: hashicorp/terraform:1.0.7
  MODULE_PIPELINE: "true"
include:
  - project: Ackee/gitlab-ci-templates
    ref: feat/62547-terraform-parallelism
    file: terraform/pipeline.yml
