variables:
  # leave following comment to enable renovate bot for terraform image
  # renovate: datasource=docker depName=hashicorp/terraform
  TERRAFORM_IMAGE: hashicorp/terraform:1.0.9
  MODULE_PIPELINE: "true"
include:
  - project: Ackee/gitlab-ci-templates
    ref: terraform/v1.8.0
    file: terraform/pipeline.yml
